#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          12
bspc config -m VGA-1 top_padding          7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config presel_feedback_color  "#a89984"
bspc config auto_alternate       true
bspc config auto_cancel          true

NUM_MONITORS=$(xrandr -q | grep connected | wc -l)

if [ $NUM_MONITORS -eq '1' ] ; then
    bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 10
elif [ $NUM_MONITORS -eq '2' ] ; then
    bspc monitor VGA-1 -d 1 2 3 4 5
    bspc monitor VGA-2 -d 6 7 8 9 10
elif [ $NUM_MONITORS -eq '3' ] ; then
    bspc monitor VGA-3 -d L1 L2 L3 L4 L5
    bspc monitor VGA-1 -d 1 2 3 4 5
    bspc monitor VGA-2 -d 6 7 8 9 10
else
    echo 'Cannot find output monitor'
fi

feh --bg-fill ~/.wallpaper.jpg

xrdb ~/.Xresources

xcompmgr &

panel &
