runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()


"Colors and syntax
set t_Co=256
let g:hybrid_use_Xresources = 1
colorscheme hybrid
syntax on
set number

"Tabs
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

set mouse=a
filetype indent plugin on
set visualbell
set ruler
set autoindent
set nowrap
execute "set colorcolumn=" . join(range(90,335),',')
