call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
Plug 'Valloric/YouCompleteMe', {'do': './install.py'}
Plug 'w0rp/ale'
Plug 'vim-airline/vim-airline'
Plug 'ntpeters/vim-better-whitespace'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-abolish'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'jmcantrell/vim-virtualenv'
Plug 'editorconfig/editorconfig-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'shime/vim-livedown'
Plug 'pangloss/vim-javascript'
Plug 'vim-scripts/MultipleSearch'

call plug#end()

set clipboard=unnamed


"Colors and syntax
set background=dark
set t_Co=256
"let g:hybrid_use_Xresources = 1
colorscheme gruvbox
syntax on
set number

set splitright
set t_vb=

"Tabs
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

set mouse=a
filetype indent plugin on
set visualbell
set ruler
set autoindent
set nowrap
set hlsearch

let line_length = 100
"Colors on right
execute "set colorcolumn=" . join(range(line_length+1,335),',')
"Make ale flake8 accept line lengths up to 100
let g:ale_python_flake8_args = "--max-line-length=" . string(line_length)

"Load indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size =2
"
"Air line
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='gruvbox'

let g:ctrlp_open_multiple_files = 'ij'
let g:ctrlp_tabpage_position = 'al'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
let g:ctrlp_custom_ignore = '\v[\/](node_modules|build)|(\.(swp|git))$'
set laststatus=2

" Set ts file to javascript syntax
autocmd BufNewFile,BufRead *.ts set syntax=javascript


let g:ycm_python_binary_path = 'python'

vmap <F7> :w !xclip<CR><CR>
map <S-F7> :r !xclip -o<CR>

tab all

" set a different locations for backups to allow react scripts livereload to
" continue to work
set backupdir-=.
set backupdir^=~/tmp,/tmp

" keep the left gutter open, so it doesn't move my text to the right while I'm
" typing
autocmd BufEnter * sign define dummy
autocmd BufEnter * execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')

