call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
Plug 'davidhalter/jedi-vim'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'ntpeters/vim-better-whitespace'
Plug 'tpope/vim-fugitive'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'jmcantrell/vim-virtualenv'
Plug 'editorconfig/editorconfig-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'shime/vim-livedown'
Plug 'pangloss/vim-javascript'
Plug 'mvx/vim-jsx'

call plug#end()


"Colors and syntax
set background=dark
set t_Co=256
"let g:hybrid_use_Xresources = 1
colorscheme gruvbox
syntax on
set number

"Tabs
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

set mouse=a
filetype indent plugin on
set visualbell
set ruler
set autoindent
set nowrap
set hlsearch

"Colors on right
execute "set colorcolumn=" . join(range(100,335),',')
"Make syntastic accept line lengths up to 100
let g:syntastic_python_flake8_args = "--max-line-length=100"

"Load indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size =2
"
"Air line
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='gruvbox'
let g:ctrlp_open_multiple_files = 'ij'
let g:ctrlp_tabpage_position = 'al'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
let g:ctrlp_custom_ignore = '\v[\/](node_modules|build)|(\.(swp|git))$'
set laststatus=2

" Set ts file to javascript syntax
autocmd BufNewFile,BufRead *.ts set syntax=javascript


" DISABLE JEDI VIM
"let g:jedi#auto_initialization = 0
"
vmap <F7> :w !xclip<CR><CR>
map <S-F7> :r !xclip -o<CR>

tab all

" set a different locations for backups to allow react scripts livereload to
" continue to work
set backupdir-=.
set backupdir^=~/tmp,/tmp
