#! /bin/sh



if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config -m DP-1-1 top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
panel_date > "$PANEL_FIFO" &
#clock -sf 'S%a %b %d, %G %H:%M' > "$PANEL_FIFO" &
#panel_battery > "$PANEL_FIFO" &
#panel_volume > "$PANEL_FIFO" &
panel_cpu > "$PANEL_FIFO" &
panel_memory > "$PANEL_FIFO" &

. panel_colors


geometry=x$PANEL_HEIGHT
NUM_MONITORS=$(xrandr -q | grep connected | wc -l)
if [ $NUM_MONITORS -eq '2' ] ; then
    MONITOR=DP-1-1
    xRes=$(xrandr -q | grep -A1 $MONITOR | grep -v $MONITOR | sed 's/\(x\|*\|+\|.00\)/ /g;s/^[ \t]*//;s/[ \t]*$//;s/ \+/ /g' |  awk '{print $1;}')
    geometry=$xRes$geometry
elif [ $NUM_MONITORS -eq '3' ] ; then
    geometry=$geometry+
    MONITOR=VGA-3
    offsetRes=$(xrandr -q | grep -A1 $MONITOR | grep -v $MONITOR | sed 's/\(x\|*\|+\|.00\)/ /g;s/^[ \t]*//;s/[ \t]*$//;s/ \+/ /g' |  awk '{print $1;}')

    MONITOR=DP-1-1
    mainRes=$(xrandr -q | grep -A1 $MONITOR | grep -v $MONITOR | sed 's/\(x\|*\|+\|.00\)/ /g;s/^[ \t]*//;s/[ \t]*$//;s/ \+/ /g' |  awk '{print $1;}')
    geometry=$mainRes$geometry$offsetRes
    echo $geometry
fi

panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g $geometry -f "Inconsolata:size=9" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
